### ISSUE TITLE
panthor.patch fails validity check

### ISSUE THREAD

**Issue by grant-cl** [7Ji-PKGBUILDs/linux-aarch64-rockchip-bsp6.1-joshua-git#2]
Looks like missing last character off sha512sum

PKGBUILD: 'c564ba067af52de0735bfb494d32ecbde70bd317bf0a819a36fa078ab2fd11e83fde6350573f8caa9a88a1c26f59106e6afcf318aaf25ccbc932633d5281253'

$ sha512sum panthor.patch 
c564ba067af52de0735bfb494d32ecbde70bd317bf0a819a36fa078ab2fd11e83fde6350573f8caa9a88a1c26f59106e6afcf318aaf25ccbc932633d52812538  panthor.patch

**Comment by hbiyik** [comment]
ugh, just noticed that. I think i messed up something.

**Comment by hbiyik** [comment]
fixed in ad788683cf485a7c8173b315c165eb862de86c5f
